# Generated by Django 3.1.4 on 2023-01-31 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20230131_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='createdt',
        ),
        migrations.AddField(
            model_name='review',
            name='createdAt',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
